### ISSUE TITLE
AI Opponent Behavior

### ISSUE THREAD

**Issue by trelkins3** [OSU-CS361-W17/group13_project1#5]
- Allow AI opponent to either randomly or statically place ships at the beginning of the game (could potentially use same method as player, but with static inputs)
- Allow AI opponent to take turns and fire at player (can also use the same method as the player firing, based on server code and passing inputs), it's uncertain how random or precise we want this

Currently a 'low level' AI that shoots randomly is technically fine, but if you're feeling adventurous feel free to program a real battleship AI.

**Comment by crs9011** [comment]
Thoughts:

Randomizing ship placement will be easy - no need to reduce complexity to static input. 
Firing will be more difficult - I'm thinking it'll be mostly dumb and random, though with the caveat that if it does hit an enemy ship, it will focus fire systematically around that area until the ship is sunk.

**Comment by Chirod** [comment]
Isn't this pre-implemented?

**Comment by trelkins3** [comment]
Not sure - where do you think it's already implemented? Admittedly I haven't looked at the front-end code yet.

**Comment by Chirod** [comment]
I believe the front end controls the ai, and tells the backend to adjust the model based off of either a player or cpu action. taking care of one should take care of the other.

**Comment by trelkins3** [comment]
According to the project Readme, the back-end is responsible for taking the computer shot and updating the game model accordingly.

On the topic of ship placement - their JSON example has statically determined start positions for computer ships, which I think means that we'll have to determine that on the back-end as well when we create the game model.
